server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/edusystem?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 410520
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,file:${web.upload-path}
  mvc:
    static-path-pattern: /files/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
      proxy-target-class: true

mybatis-plus:
  type-aliases-package: edusystem.org.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
app:
  uploadFolder: D://icode/files/homeworkFiles/
  previewPath: http://127.0.0.1:8000/files/homeworkFiles
  resumeFolder: D://icode/files/submitFiles/
  resumePath: http://127.0.0.1:8000/files/submitFiles
web:
  upload-path: D://icode/files/